name: "Load Docker Image"
description: "Load image from downloaded artifact" 
inputs:
  name:
    description: "The name of the artifact"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Download image artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: /tmp/${{ inputs.name }}.tar
    - name: Load image
      run: docker load --input /tmp/${{ inputs.name }}.tar
      shell: bash
